p:background.o coin.o collision.o def.o jouer.o main.o mouvement.o personnage.o scroling.o coeur.o enemi.o
	gcc background.o coin.o collision.o def.o jouer.o main.o mouvement.o personnage.o scroling.o coeur.o enemi.o -o p -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
background.o :background.c
	gcc -c background.c
coin.o :coin.c
	gcc -c coin.c
collision.o :collision.c
	gcc -c collision.c
def.o :def.c
	gcc -c def.c
jouer.o :jouer.c
	gcc -c jouer.c
main.o :main.c
	gcc -c main.c
mouvement.o :mouvement.c
	gcc -c mouvement.c
personnage.o :personnage.c
	gcc -c personnage.c
scroling.o :scroling.c
	gcc -c scroling.c
coeur.o :coeur.c
	gcc -c coeur.c
enemi.o :enemi.c
	gcc -c enemi.c
